version: "3.2"

services: 
  webappexample:
    container_name: webappexample
    build:
      context: ./WebappExample
    command: julia --project="/opt/julia" serve/webappserve.jl
    ports:
      - "81:8080"

  webappvue:
    image: nginx:alpine
    container_name: webappvue

    volumes:
      - ./webapp-vue/dist:/usr/share/nginx/html
    ports:
      - "80:80"